image: atlassian/default-image:2

pipelines:
  branches:
    main:
      - step:
          name: Deploy to EC2
          caches:
            - node
          script:
            # Instalar SSH e preparar a chave privada
            - apt-get update && apt-get install -y openssh-client

            # Executar o script de deploy na instância EC2
            - ssh -o StrictHostKeyChecking=no ubuntu@100.26.208.201 'bash -s' < deploy_script.sh
definitions:
  caches:
    node: ~/.npm
