image: atlassian/default-image:2

pipelines:
  branches:
    main:
      - step:
          name: Deploy to EC2
          caches:
            - node
          script:
            - apt-get update && apt-get install -y ssh
            - chmod 600 id_rsa
            - ssh -i "$SSH_PRIVATE_KEY" -o StrictHostKeyChecking=no ubuntu@100.26.208.201 'bash -s' < deploy_script.sh

definitions:
  caches:
    node: ~/.npm
