image: atlassian/default-image:2

pipelines:
  branches:
    main:
      - step:
          name: Deploy to EC2
          caches:
            - node
          script:
            - apt-get update && apt-get install -y ssh
            - scp -o StrictHostKeyChecking=no -r * ubuntu@100.26.208.201:/face-recognition-engine/
            - ssh -o StrictHostKeyChecking=no ubuntu@100.26.208.201 'bash -s' < deploy_script.sh

definitions:
  caches:
    node: ~/.npm
